# General Info
site_name: Compiladores
site_description: Ciencias de la Computacion 4 - Compiladores
site_author: CC-4
site_url: https://cc-4.github.io/

# Repository
edit_uri: edit/master/page/es/docs
repo_name: cc-4/cc-4.github.io
repo_url: https://github.com/cc-4/cc-4.github.io

# Copyright
copyright: 'CC-4'

# Theme Configuration
theme:
  name: material
  language: es
  custom_dir: ../assets


# Customization
extra:
  social:
    - type: github
      link: https://github.com/cc-4/

extra_css:
  - stylesheets/emoji.css
  - stylesheets/kbd.css
  - stylesheets/button.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
  - js/latex.js
  - js/python.js


# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Inicio: index.md
  - Laboratorios:
    - '1: COOL': labs/lab01.md
    - '2: jLex': labs/lab02.md
    - '3: RDP': labs/lab03.md
    - '4: cup': labs/lab04.md
    - '5: SymbolTable': labs/lab05.md
    - '6: Semantic 1': labs/lab06.md
    - '7: Semantic 2': labs/lab07.md
    - '8: RISC-V': labs/lab08.md
    - '9: Codegen 1': labs/lab09.md
    - '10: Codegen 2': labs/lab10.md
    - '11: Optimizaciones': labs/lab11.md
  - Proyectos:
    - '0: Instalacion': projs/proj00.md
    - '1: Lexer': projs/proj01.md
    - '2: Parser': projs/proj02.md
    - '3: Semantic' : projs/proj03.md
    - '4: Codegen' : projs/proj04.md
